#!/bin/bash
set -e
set -o pipefail

OPTS=$(getopt --options sidrca --longoptions short,id,description,release,codename,all --name 'lsb_release' -- "$@")
eval set -- "${OPTS}"

if [[ $? != 0 ]]; then
    echo "Failed parsing options." >&2
    exit 1
fi
if [[ -z ${1} ]]; then
    echo "No LSB modules are available."
    exit 0
fi

SHORT=0
ACTION=

while true; do
    case "${1}" in 
        -s | --short)
            SHORT=1; shift ;;
        -i | --id)
            ACTION=id; shift ;;
        -d | --description)
            ACTION=description; shift ;;
        -r | --release)
            ACTION=release; shift ;;
        -c | --codename)
            ACTION=codename; shift ;;
        -a | --all)
            ACTION=all; shift ;;

        --) shift; break ;;
        *) break ;;
    esac
done


get_info()
{
    cat /etc/os-release | grep "^$1=" | head -n1 | cut -d= -f2 | sed -e 's/^"//' -e 's/"$//'
}

case "${ACTION}" in
    id)
        [[ ${SHORT} -eq 1 ]] || echo -n "Distributor ID:	"
        echo $(get_info NAME)
        exit 0
        ;;
    description)
        [[ ${SHORT} -eq 1 ]] || echo -n "Description:	"
        echo $(get_info PRETTY_NAME)
        exit 0
        ;;
    release)
        [[ ${SHORT} -eq 1 ]] || echo -n "Release:	"
        echo $(get_info VERSION_ID)
        exit 0
        ;;
    codename)
        [[ ${SHORT} -eq 1 ]] || echo -n "Codename:	"
        echo $(get_info ID)
        exit 0
        ;;

    all)
        echo "No LSB modules are available."
        [[ ${SHORT} -eq 1 ]] || echo -n "Distributor ID:	"
        echo $(get_info NAME)
        [[ ${SHORT} -eq 1 ]] || echo -n "Description:	"
        echo $(get_info PRETTY_NAME)
        [[ ${SHORT} -eq 1 ]] || echo -n "Release:	"
        echo $(get_info VERSION_ID)
        [[ ${SHORT} -eq 1 ]] || echo -n "Codename:	"
        echo $(get_info ID)
        exit 0
        ;;

    *)
        echo "No LSB modules are available."
        exit 0
        ;;
esac
